version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - JWT_SECRET=please-change-me
      - ENABLE_TFIDF=1
    volumes:
      - ./:/app
